site_name: My Docs

theme:
  name: material
  palette:
    primary: cyan
  features:
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GradProjectHub/GradProject

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - exclude:
      glob:
        - .github/*
      include:
        - .github/ISSUE_TEMPLATE/**/*