name: エラー等の解決・改善・リファクタ
description: エラーの解決やリファクタはこちらにお願いします。
body:
  - type: textarea
    id: background
    attributes:
      label: 背景
      description: どのような課題を抱えてissueを立てたのか、経緯や前提を記載してください。
    validations:
      required: true
  - type: textarea
    id: do
    attributes:
      label: やること
      description: このissueで取り組むこと（目標）を記載してください。
    validations:
      required: true
  
  - type: textarea
    id: supplement
    attributes:
      label: 補足