name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Install mkdocs and plugin
        run: pip install mkdocs-material mkdocs-exclude

      - name: Show mkdocs.yml for debugging
        run: cat mkdocs.yml

      - name: Build MkDocs site
        run: mkdocs build --verbose

      - name: Prepare for deployment to GitHub Pages
        run: |
          mv site _site
          cp -r .github/ISSUE_TEMPLATE _site/.github/.ISSUE_TEMPLATE

      - name: Deploy to GitHub Pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          cd _site
          git init
          git remote add origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy with MkDocs"
          git push --force origin gh-pages